export const POST_START = "AUTH_START";
export const POST_SUCCESS = "AUTH_SUCCESS";
export const POST_FAIL = "AUTH_FAIL";

export const GENERAL_COLOR_CHANGED = "GENERAL_COLOR_CHANGED";
export const GENERAL_LANGUAGE_SET = "GENERAL_LANGUAGE_SET";

export const GENERAL_ACTIVE_PAGE_CHANGED = "GENERAL_ACTIVE_PAGE_CHANGED";
