# Generated by Django 2.2.3 on 2019-11-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191103_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact_en',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact_fa',
        ),
    ]
