# Generated by Django 2.2.3 on 2019-10-30 11:01

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('name_fa', models.CharField(blank=True, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('content_fa', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('short_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('short_content_fa', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('short_content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('lang', models.CharField(default='fa', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='picture/')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='past_memory.Post')),
            ],
        ),
    ]
