# Generated by Django 2.2.3 on 2019-11-03 08:12

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import past_memory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('past_memory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('name_fa', models.CharField(blank=True, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('uuid', models.CharField(blank=True, default=past_memory.models.generate_uuid, max_length=32, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('content_fa', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('short_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('short_content_fa', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('short_content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('lang', models.CharField(default='fa', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('create_resume', 'Can add, edit, delete, update a general survey'), ('create_pdf', 'Can create a pdf from their information')],
            },
        ),
        migrations.RemoveField(
            model_name='picture',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='picture',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='past_memory.Resume'),
        ),
    ]
