# Generated by Django 2.2.3 on 2019-11-03 10:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past_memory', '0002_auto_20191103_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='short_content',
            new_name='abstract',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='short_content_en',
            new_name='abstract_en',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='short_content_fa',
            new_name='abstract_fa',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='content',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='content_en',
            new_name='introduce',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='content_fa',
            new_name='introduce_en',
        ),
        migrations.AddField(
            model_name='resume',
            name='introduce_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
