# Generated by Django 2.2.3 on 2019-11-03 10:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past_memory', '0003_auto_20191103_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='contact',
            new_name='contact_info',
        ),
        migrations.AddField(
            model_name='resume',
            name='contact_info_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='contact_info_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
