# Generated by Django 2.2.3 on 2019-11-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past_memory', '0008_auto_20191103_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_en',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_fa',
        ),
    ]
