# Generated by Django 2.2.3 on 2019-11-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_memory', '0009_auto_20191103_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='work_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='work_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
