# Generated by Django 2.2.3 on 2019-11-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past_memory', '0010_auto_20191103_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='name',
        ),
    ]
