# Generated by Django 2.2.3 on 2019-11-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_memory', '0013_auto_20191108_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
