# Generated by Django 2.2.3 on 2019-11-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_memory', '0014_education_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='experiences/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
    ]
